name: Sync files to S3

on:
    push:
      branches: [ "master" ]
    pull_request:

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read

jobs:
    sync:
        name: 'Sync'
        runs-on: ubuntu-latest
        environment: Prod

        steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::675853243185:role/GithubActionsTerraform
            aws-region: eu-west-1     

        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        - name: Sync
          run: aws s3 sync $GITHUB_WORKSPACE s3://www.joeybrayshaw.com/ --size-only
